### ISSUE TITLE
RAPL zone hierarchy

### ISSUE THREAD

**Issue by amkozlov** [powercap/powercap#3] opened 2020-05-29 15:26 UTC
Dear developers,

could you please help me grasp the logic behind RAPL zone hierarchy?

E.g., on my laptop (i7-8550U) I have the following layout:

```
|-intel-rapl:0 package      ->  (CPU socket)
| |-- intel-rapl:0:0 cores  ->  (CPU cores)
| |-- intel-rapl:0:1 uncore ->  (integrated graphics etc.)
| |-- intel-rapl:0:2 DRAM   ->  (memory, per socket, but *not* included in package value above)
|-intel-rapl:1 psys         ->  (whole system, ie includes package and DRAM)
```

Do I understand correctly that `energy_uj` value for the `package` zone also includes `cores` and `uncore`, but does not include `DRAM`? And that `psys` value includes `package` and `DRAM`?
It looks, well, counter-intuitive, but seems to be the case according to my observations...

Background: I'm trying to implement energy consumption monitoring for my program, and so I'm interested in the *overall* system power.  RAPL sysfs seems to be the only practical option, since it does not require root privileges. So it looked simple and straightforward, until I realized that I cannot just add up values from all zones to get system-wide power/energy.

Many thanks in advance! I understand that this question is not directly related to your code, but your help will be greatly appreciated!

Alexey

**Comment by connorimes** [comment] 2020-05-29 15:46
Hi Alexey.  You have a system with a `psys` zone -- I've not seen one of these before so this is exciting.  Can you please provide the output for the following commands for me:

```
tree /sys/class/powercap/intel-rapl
```
and
```
powercap-info -p intel-rapl
```

You are correct that the `package` zone energy counter should include the energy consumed by the `core` and `uncore` zones.  To the best of my knowledge, you are also correct that it does _not_ include `dram`.  I expect this is the counter-intuitive part, since the Linux powercap interface is structured as a tree, and logically a parent node should account for its children.  But in this case, the DRAM is not actually on the CPU.  I expect the reason that DRAM is included as a subzone of a package is because the package has a memory controller that is "local" (in a NUMA sense) to a subset of the system DRAM, so the power/energy measurements RAPL collects are for that portion of the DRAM.

The `psys` zone is more of a mystery---the limited documentation I've seen on it seems to be intentionally vague.  What exactly is measures may depend on your system.  You might consider looking for detailed tech specs on your system (and in particular, the motherboard).  My hope is that it measures the entire CPU socket, DRAM, and perhaps even other peripherals like PCI devices (e.g., off-chip GPUs, audio, network cards like ethernet and wifi and bluetooth, USB).

You might consider measuring the power of each zone individually and seeing how they add up.  For example if `package` and `dram` power sum up to less than the `psys` power, then perhaps `psys` accounts for both, although that is not conclusive.  If, however, their sum exceeds the `psys` power, it is an indication that `psys` is not accounting for both (or perhaps either) of those zones.

**Comment by amkozlov** [comment] 2020-05-29 16:04
Hi Connor,

thanks for your prompt and detailed response!

It seems like `psys` is usually available on (modern?) laptops. In my case, it's ThinkPad T480s with.Kaby Lake CPU. I'm also attaching the output of the commands you requested.

Both energy consumption and power limit (90W) for the `psys` zone are higher than the sum of `package` and `dram`, so I assume it should be the "total" power indeed.

Have you actually ever seen any other zones - except `package`, `dram`, `core`, `uncore` and `psys` - in your practice? Is it so that OEMs are free to define arbitrary zones for their hardware, and RAPL standard does not impose any requirements regarding naming, what is measured and hierarchy ("what includes what")?

[powercap-info.txt](https://github.com/powercap/powercap/files/4702851/powercap-info.txt)
[rapl-tree.txt](https://github.com/powercap/powercap/files/4702852/rapl-tree.txt)

**Comment by amkozlov** [comment] 2020-05-30 01:38
I'm glad to hear that my input was helpful! It's also comforting that at least zone types are fixed, so I hope my code will work on most existing systems. But do you by any chance have an example of the tree with those new `package-%d-die-%d` zones?

Another annoying thing with RAPL is that energy counters can overflow pretty fast (<1h), and as far as I can tell, there is no "overflow counter", ie it does not keep track of how many times counter has been reset. Hence, I cannot simply compare `energy_uj` at program start vs. program end, but have to constantly poll energy counters while program is running, to make sure I catch all overflows. This makes things more complicated than they have to be, so I wonder why RAPL/powercap has this weird overflow behavior? I guess Linux powercap could implement overflow counter in software really easy, even if there is no respective HW counter in the CPU.  Or maybe there is an application-level workaround which I can use to avoid polling?

BTW I'm also reading your CoPPer paper now, which is super informative - a while ago, I was trying to understand why DVFS does not work anymore on Skylake and CascadeLake, now I finally have the answer :) .

**Comment by connorimes** [comment] 2020-05-30 02:18
I caution against believing that zone types are truly fixed, since more may be added in the future.  For example, `psys` was not an original `intel-rapl` zone type.  But at some point you may have to settle for "good enough."

I don't have any examples of `package-%d-die-%d` systems since I haven't seen one myself.  I saw documentation about a recent Intel CPU architecture having multiple dies in the same package for some high-end versions of the chip.  I think this may be Cascade Lake [1], but don't quote me on that.  I saw the `package-%d-die-%d` name format change within the Linux kernel, and based on this I believe the powercap interface will simply "replace" the existing `package-%d` zone name format on such systems, so you just need to support the two string formats when checking the zone name.

[1] https://en.wikichip.org/wiki/intel/microarchitectures/cascade_lake

You are also correct about the counters rolling over.  This is because the counters are encoded in hardware MSRs like I mentioned earlier, which have a finite number of bits available and must trade off precision for range (see the Intel Software Developer's Manual, Section 14.9).  The only way to make sure you don't miss readings is to poll, and this would never be implemented in the kernel.  Your estimate of <1h is not nearly aggressive enough, I believe that some high power CPUs under load can roll over in <1m, perhaps even <10s.  The Linux powercap interface allows for control types to expose `power_uw` instead of `energy_uj`, but this has the same problem in that you'd have to poll it at it's refresh interval to not miss changes, and that could be even more problematic (no control type uses `power_uw` though, but I've worked with other hardware monitors that expose power instead of energy and it's a pain).

I'm glad you like the CoPPer paper.  You might also be interested in the EnergyMon project [2, 3].  It predates the CoPPer work and this powercap project.  I'd like to update it for more complete RAPL support using this powercap interface, but I just haven't gotten to it (e.g., it's `rapl` interface uses Linux powercap, but isn't flexible and assumes `package` is the top-level zone, which obviously isn't the case anymore with the introduction of `psys`).  The `raplcap-msr` implementation there currently has the best RAPL support.

[2] https://doi.org/10.1145/2950290.2983956
[3] https://github.com/energymon/energymon

**Comment by amkozlov** [comment] 2020-06-02 01:10
> I caution against believing that zone types are truly fixed, since more may be added in the future. For example, `psys` was not an original `intel-rapl` zone type. But at some point you may have to settle for "good enough."

exactly, covering all zones that we have now is certainly good enough for me.
 
> I don't have any examples of `package-%d-die-%d` systems since I haven't seen one myself. I saw documentation about a recent Intel CPU architecture having multiple dies in the same package for some high-end versions of the chip. I think this may be Cascade Lake [1], but don't quote me on that. I saw the `package-%d-die-%d` name format change within the Linux kernel, and based on this I believe the powercap interface will simply "replace" the existing `package-%d` zone name format on such systems, so you just need to support the two string formats when checking the zone name.

Interesting, I have access to a Cascade Lake system (Xeon Platinum 8260), and it has the "usual" `package` + `dram` layout.

> You are also correct about the counters rolling over. This is because the counters are encoded in hardware MSRs like I mentioned earlier, which have a finite number of bits available and must trade off precision for range (see the Intel Software Developer's Manual, Section 14.9). The only way to make sure you don't miss readings is to poll, and this would never be implemented in the kernel. Your estimate of <1h is not nearly aggressive enough, I believe that some high power CPUs under load can roll over in <1m, perhaps even <10s. 

Well, on my system `max_energy_range_uj` is set to `262143328850 uJ` , which is ~`72.8 Wh`. So even on a high power CPU with 150-300W consumption, it should take 15-30mins to overflow. I mean, of course the counter could overflow much faster depending on the initial value, but the really nasty part is when it overflows *twice*. Because then I have no way to detect if it overflowed twice or 10 times (except with polling). I think Intel saved a few bits in the wrong place here, unfortunately.

>The Linux powercap interface allows for control types to expose `power_uw` instead of `energy_uj`, but this has the same problem in that you'd have to poll it at it's refresh interval to not miss changes, and that could be even more problematic (no control type uses `power_uw` though, but I've worked with other hardware monitors that expose power instead of energy and it's a pain).

OK I guess I'm beginning to understand, so Linux powercap driver does not perform any register polling by itself, but every time I read `/sysfs/.../energy_uj` file, the respective callback function reads MSR register and returns the actual counter value? And so polling in the driver would incur additional overhead, if nobody is reading `energy_uj` (which is probably 99.9% of the tim)? OTOH for the overflow detection, it would be enough to poll every 60s or more (given my calculation above is correct) - and the overhead of this should be really negligible. 

> I'm glad you like the CoPPer paper. You might also be interested in the EnergyMon project [2, 3]. It predates the CoPPer work and this powercap project. I'd like to update it for more complete RAPL support using this powercap interface, but I just haven't gotten to it (e.g., it's `rapl` interface uses Linux powercap, but isn't flexible and assumes `package` is the top-level zone, which obviously isn't the case anymore with the introduction of `psys`). The `raplcap-msr` implementation there currently has the best RAPL support.

Thank you! EnergyMon is actually doing pretty much what I need, but I already spent time on my own primitive implementation, which now also handles `psys` properly :) 

I see that EnergyMon supports a lot of external power meters, which is great for people who are working on power efficiency themselves, but this hardware is rather unlikely to see in the common clusters where regular users would run their codes. So I wonder whether you thought about integrating the IPMI [1] as a data source? The benefit would be that IPMI is supported by many server-class motherboards, and provides overall system power (no confusion with zones).

[1] http://www.gnu.org/software/freeipmi/freeipmi-faq.html

**Comment by connorimes** [comment] 2020-06-02 13:26
I think only a small subset of Cascade Lake systems have this multi-package configuration.  See this particular section of the wiki page I linked earlier [1].  Also, just because a configuration is documented doesn't mean it's commercially available (yet?)---I haven't checked.

[1] https://en.wikichip.org/wiki/intel/microarchitectures/cascade_lake#Higher_core-count_multi-chip_processors

Re: overflow - that time range should hopefully make your overflow problem manageable.  The multiple overflow concern also exists in EnergyMon, but I haven't tried to address it since the API is primarily designed for frequent reads by the user, so missing multiple overflows just isn't a serious concern for its intended use case.
The MSR energy usage data is encoded, and then---explained simply---scaled by another value to produce the actual microujoule value.  This scalar value can be different for different processor models (it's stored in another MSR).  So if the scalar value is relatively small---meaning the energy counter granularity is finer---then the max energy value will be lower since the number of bits available for the encoded energy counter value in the MSR is fixed.  I don't have concrete data available to quantify how long this might actually be on some systems though.
IIRC, I've seen the `max_energy_range_uj` file simply return `0` on some (probably older) systems.  So keep that in possibility mind if you depend on it to determine your polling frequency -- you'll have to fall back on another heuristic.

Thanks for the pointer to IPMI.  I've heard of it but have not used it before.  I'll add it to my EnergyMon wishlist :)

Since you have access to a PSYS systems, perhaps you can test a couple of quick things for me on it?  I made some changes over the weekend, in particular to patch #4, but can't test it myself.  I'm also curious if (1) the kernel module name has changed due to Linux kernel internal refactoring following the introduction of the `intel-rapl-mmio` control type, which perhaps one of your newer systems support (probably Ice Lake and newer, but perhaps also Cascade Lake), and (2) if your system has `intel-rapl-mmio` support.
Specifically, can you please pull the HEAD of this powercap repo, build, and share with me the output of the following on your newest PSYS-enabled system?  I'd really appreciate it.

```
uname -r
lsmod | grep -E "rapl|thermal"
ls /sys/class/powercap
# from the powercap directory:
git rev-parse HEAD
# from the powercap build directory:
./powercap-rapl-test
```

**Comment by amkozlov** [comment] 2020-06-02 14:59
> I think only a small subset of Cascade Lake systems have this multi-package configuration. See this particular section of the wiki page I linked earlier [1]. Also, just because a configuration is documented doesn't mean it's commercially available (yet?)---I haven't checked.

OK I see, so apparently it will apply to CascadeLake **AP** systems, and I only have CascadeLake **SP** withing reach.

> IIRC, I've seen the `max_energy_range_uj` file simply return `0` on some (probably older) systems. So keep that in possibility mind if you depend on it to determine your polling frequency -- you'll have to fall back on another heuristic.

That's a good point, thank you!

> Since you have access to a PSYS systems, perhaps you can test a couple of quick things for me on it? I made some changes over the weekend, in particular to patch #4, but can't test it myself. I'm also curious if (1) the kernel module name has changed due to Linux kernel internal refactoring following the introduction of the `intel-rapl-mmio` control type, which perhaps one of your newer systems support (probably Ice Lake and newer, but perhaps also Cascade Lake), and (2) if your system has `intel-rapl-mmio` support.

I can't see `intel-rapl-mmio` on any of "my" systems...

> Specifically, can you please pull the HEAD of this powercap repo, build, and share with me the output of the following on your newest PSYS-enabled system? I'd really appreciate it.

Sure, please see attachment. psys zone is `intel-rapl:1`, but wasn't detected for some reason.

[4connor.txt](https://github.com/powercap/powercap/files/4717937/4connor.txt)

**Comment by connorimes** [comment] 2020-06-02 15:39
Thanks for running those.  It looks like your kernel is too old to support `intel-rapl-mmio`, which also means it doesn't tell me if the kernel module name changed.  I think we'd need at least kernel 5.3.  Oh well.

It looks like the test found the 2 top-level zones and initialized them correctly, but the code was written to only actually test for the first one.  Dang---my bad.  I've modified `powercap-rapl-test` to output results for every top-level zone now.  Would you mind pulling the latest, rebuilding, and running again from the build directory?:

```
./powercap-rapl-test
```

**Comment by amkozlov** [comment] 2020-06-02 15:55
does it look better now? :)

[4connor.txt](https://github.com/powercap/powercap/files/4718259/4connor.txt)

**Comment by connorimes** [comment] 2020-06-02 16:15
It does look better now -- it verifies that the patch for #4 works as expected.  I really appreciate you taking the time to test these things for me.

One of the big challenges in writing code that requires testing on a variety of different platforms is that I never have access to all the platforms that need to be supported.  Another challenge is that the platforms continue to evolve!

I'm curious how you're actually using this powercap project.  E.g., are you using the binaries and/or linking against the powercap library?  In deployment or just for test/verification of your own code?  Which binaries/interfaces are you actually using?

**Comment by amkozlov** [comment] 2020-06-03 13:31
> It does look better now -- it verifies that the patch for #4 works as expected. I really appreciate you taking the time to test these things for me.

You're welcome, and I also appreciate that you took so much time to explain me RAPL quirks!

> One of the big challenges in writing code that requires testing on a variety of different platforms is that I never have access to all the platforms that need to be supported. Another challenge is that the platforms continue to evolve!

Well that's how it is, so software has to evolve along...

> I'm curious how you're actually using this powercap project. E.g., are you using the binaries and/or linking against the powercap library? In deployment or just for test/verification of your own code? Which binaries/interfaces are you actually using?

I came across powercap while looking for info on RAPL and its cryptic zone hierarchy.  I'm not directly using powercap at the moment. Before discovering powercap/energymon, I already implemented a very simple RAPL wrapper suited for my purposes (https://github.com/amkozlov/raxml-ng/blob/coarse/src/util/EnergyMonitor.cpp).  My goal was to measure the overall energy consumption of the program run and show it to the user, i.e. I print something like this in my log file:

```
Elapsed time: 859.545 seconds
Consumed energy: 95.297 Wh
```
(I realize that this number is just a very rough (under)estimate, but it's fine for raising user awareness). 

My colleagues also seem to be interested in similar functionality for their codes. Now I know that `energymon` can be used for doing these measurements, although it feels a bit like an overkill. What would be ideal is a lean, header-only library (dependencies are always a pain) with a simple API, which will protect the application developer from dealing with RAPL idiosyncrasies, evolving hardware etc.

To give you some background: our software (eg https://github.com/amkozlov/raxml-ng) is used for some pretty heavy analyses that require 100,000s of CPU-hours. And colleagues next door are happily burning many MWh on simulating the universe or nanoseconds of protein interaction, training neuronal nets, and what not :) So I recently stated to look for approaches to reduce energy consumption, both in software (eg autotuning) and at the infrastructure level (eg SLURM).

**Comment by connorimes** [comment] 2020-06-03 15:04
I agree that SW has to evolve.  However, we should still be able to construct abstractions that are general and stable enough that they should not have to evolve, while still providing benefit to higher-level code (think of POSIX as an example, which has endured for decades).  The powercap library in this project has evolved over time to primarily provide bindings over the kernel's sysfs, and since the _structure_ in sysfs doesn't change, neither should the bindings.  The problem now is that RAPL-specific assumptions and coded enumerations were built into some of the interfaces---a decision that predates the desire to have this project provide a binding-only abstraction.

I'm glad to see more interest in power/energy awareness in HPC, esp. at the scheduler and application level.  The problem that you're describing is essentially what EnergyMon was designed to address -- a common interface that abstracts users from the underlying power/energy APIs and idiosyncrasies.  I'm certain your code could implement the EnergyMon API, then developers could simply swap your implementation for others depending on their needs without requiring them to modify their application code.  EnergyMon was designed for single nodes, but there is power/energy monitoring work out there intended for distributed HPC applications.  For example, see work from a colleague in grad school [1].  There are also larger efforts out there that tend to fall under the scope of exascale computing research.  None of this is intended as a sales pitch though---you should of course decide what is best for your use case!

[1] https://doi.org/10.1145/3149412.3149419

I agree that dependencies are a pain, but if you want abstracted and reusable code, then you just have to deal with it eventually.  Welcome to SW engineering!  Header-only implementations destroy the abstraction and very quickly become unwieldy.  If you're trying to avoid runtime dependency problems, the better alternative (IMO) is to simply link your code statically against the dependency, which you already had to have at compile time even for header-only dependencies.  Static linking is a common approach in HPC already since each applications tend to require building all their non-system dependencies from source anyway.

**Comment by amkozlov** [comment] 2020-06-09 18:16
> I agree that SW has to evolve. However, we should still be able to construct abstractions that are general and stable enough that they should not have to evolve, while still providing benefit to higher-level code (think of POSIX as an example, which has endured for decades).

Having energy data available through a POSIX call, eg as part of [getrusage()](https://www.man7.org/linux/man-pages/man2/getrusage.2.html) output, would be a dream, Unfortunately, nobody seems to care (enough), or maybe care too much about output being perfect, so it will probably remain a dream...

> EnergyMon was designed for single nodes, but there is power/energy monitoring work out there intended for distributed HPC applications. For example, see work from a colleague in grad school [1]. 

Thanks for the hint, although I've already read the PoLiMEr paper and found it very interesting, especially the part about userspace power-capping via msr-safe module. It's one more piece of the puzzle. And btw, there is nothing wrong with pitching your software ;)

> I agree that dependencies are a pain, but if you want abstracted and reusable code, then you just have to deal with it eventually. Welcome to SW engineering! 

I'm not quite new to SW engineering, but good advice is always welcome ;) I do use statically linked binaries whenever possible, since I also think this is the easiest way to provide seamless user experience for scientific software in HPC. When it does not work and users have to build from source (eg MPI, latest github version), even compile-time dependencies add extra overhead/complexity (if you ever worked with git submodules, you know what I mean...).    

Anyways, back to power/energy. I'm looking at this from a very pragmatic perspective, i.e. what could be *realistically* adopted for a wide range of (HPC) systems and applications? I think there are multiple use cases which might require different solutions:

1. Report overall energy for the program run (basically my case above). This is sort of cherry-on-top-nice-to-have feature, which most app developers would only consider if it's fast and easy to implement, and adds zero complexity and maintenance overhead. Like in: you drop a header in the source tree, add 2-3 function calls, and forget about it for the next 5 years, thereafter you maybe update the header to add support for newer systems. Especially in academia setting, where we don't have a luxury of separate QA or user support department, low maintenance cost is crucial. If you expect that this neat little feature could generate user questions like "why energylib is not found/has wrong version/does not compile on my system?", you'd think twice whether it's worth adding.  

2. Energy profiling and code optimization. Here, EnergyMon/PoLiMEr are perfect: you'd probably allocate some time for this task (or it could even be a separate student project), you might have access to an external power meter on the test system, and there might be no need to include EnergyMon as dependency to the production code. 
 
3. Application-level autotuning a la CoPPer. I see two practical limitations here. First, since power capping is not available to regular users by default, you'd need cooperative sysadmins who would eg install `msr-safe` module. In my experience, sysadmins are not very keen on installing something unfamiliar on a production system, let alone if it leaks permissions :) Second, every application developer has to modify their code to add autotuning support. This leads to a chicken and egg situation: app developers will be more motivated to invest their time if they know autotuning will work on many systems (and on their "home" cluster to start with), whereas admins can be easier convinced if, say, 10% energy savings can be achieved with 90% of the codes and not with just one or two. 

4. Power optimization on the system/scheduler level. Currently, this approach looks most promising to me. An autotuning plugin for e.g. SLURM could be easily installed on many clusters, will have no problems with permissions and will leave sysadmins in full control. If hardware performance counters are not suitable for tuning (I guess you say this in one of your papers) and hence application code modification is necessary, I would argue for the "inversion of control": application-specific performance counters and/or preferences can be published in some standardized form (via /dev/shm, mmap, libevent etc.), and SLURM plugin can read those data and perform the actual power capping/autotuning. As with the standard IoC pattern, this would reduce coupling. But no less important, I think this sort of application-side performance logging could be very lightweight, in terms of both coding and runtime overhead. Autotuning not (yet) supported by most systems? Not a big deal, if logging costs are negligible. We have autotuning plugin installed, but most codes don't implement logging yet? Also fine, we can fallback to HW performance counters or whatever else is available, and hopefully still get some power savings. New fancy autotuning algorithm or new hardware? Easy-peasy, we just update the plugin, and all applications will benefit immediately, no need to change code or even recompile. But enough pitching, I'm really curious to hear your opinion on this :)

**Comment by Haptein** [comment] 2021-09-21 06:35
Hello there. I stumbled on this discussion while researching the topic. I learned quite a bit, thank you. I did some measurements (i7 9750H) maybe you'll find them interesting.

Drawing power from AC:
|            | Idle     | CPU Load  | GPU Load  |
|------------|----------|-----------|-----------|
| psys:      | 1.2673 W |  6.1569 W |  5.4546 W |
| dram:      | 0.6919 W | 0.9869 W  | 2.0066 W  |
| core:      | 0.1475 W | 28.1733 W | 4.5959 W  |
| package-0: | 1.4574 W | 30.4330 W | 24.3674 W |
| uncore:    | 0.0102 W | 0.4774 W  | 17.5646 W |

and from battery:
|            | Idle     | CPU Load  |
|------------|----------|-----------|
| psys:      | 0.0000 W |  0.0000 W |
| dram:      | 0.7131 W | 0.9533 W  |
| core:      | 0.0679 W | 27.6214 W |
| package-0: | 1.4572 W | 29.7532 W |
| uncore:    | 0.0622 W | 0.3890 W  |

Psys scales with package's energy consumption but stops when on battery. I was guessing it reflected the power consumption of the power management logic and telemetry systems but it going as high as 10 W (under full CPU load, not shown in table) makes no sense to me.

**Comment by bpetit** [comment] 2023-05-22 16:16
Hi,

I have a psys domain on my machine (t480s as well, with Intel(R) Core(TM) i5-8250U, running 5.19.0-41-generic and Ubuntu 22.04.2 LTS) and would love to contribute in this investigation. energy_uj of psys in my case is much higher than core+uncore+dram.

I also have intel-rapl-mmio on this machine (since recently, I guess it was due to a recent update).

Background : developping https://github.com/hubblo-org/scaphandre/ project.

I have to read this thread completely and will do homework on psys domain, but in the mean time, if I could run tests that might be useful, I'd be glad to.

**Comment by connorimes** [comment] 2023-05-22 17:03
Hi again @bpetit. Your project looks cool! W.r.t. your comment, I think it should be expected that `energy(psys) >= energy(core+uncore+dram)` since `psys` is supposed to instrument more of the system than CPUs and DRAM.  I believe it's platform-specific exactly what `psys` covers (e.g., does it cover PCIe slots? I don't think it's defined, but it might).

I'd be interested if you learn anything new about `psys`, but I think we now at least understand how it fits into Linux's powercap sysfs API.  I'm therefore going to close this issue since I think the original questions are answered, but feel free to continue the discussion with anything you learn or open new issues as needed!

P.S. On a related note: if you have access to a Sapphire Rapids CPU, I'd be curious to know if the `psys` quirks handled in the Linux kernel are actually real---I've yet to get a satisfactory answer [1].  You'll need to handle these kinds of exceptions in your own MSR driver code.

[1] https://community.intel.com/t5/Software-Tuning-Performance/RAPL-quirks-on-Sapphire-Rapids/m-p/1446761

**Closed by connorimes** 2023-05-22 17:03 UTC
Labels: question
